# Generated by Django 5.1.13 on 2026-01-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank", "0002_verificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="external_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="account",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("TRANSFER", "Transfer"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("EXTERNAL_TRANSFER", "External Transfer"),
                ],
                max_length=20,
            ),
        ),
    ]
