# Generated by Django 5.0.6 on 2026-01-24 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_ledgerentry_external_data_alter_account_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_type', models.CharField(choices=[('BTC', 'Bitcoin'), ('USDT', 'Tether (USDT)'), ('ETH', 'Ethereum')], max_length=10)),
                ('network', models.CharField(choices=[('BITCOIN', 'Bitcoin Network'), ('ERC20', 'Ethereum (ERC-20)'), ('TRC20', 'Tron (TRC-20)'), ('BEP20', 'Binance Smart Chain (BEP-20)'), ('ETHEREUM', 'Ethereum Network')], max_length=20)),
                ('wallet_address', models.CharField(max_length=255)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='crypto_qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=10.0, max_digits=12)),
                ('instructions', models.TextField(blank=True, help_text='Custom instructions for users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['crypto_type', 'network'],
                'unique_together': {('crypto_type', 'network')},
            },
        ),
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=255)),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='crypto_proofs/')),
                ('verification_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING_VERIFICATION', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_PAYMENT', max_length=30)),
                ('admin_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to='bank.customerprofile')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposit', to='bank.ledgerentry')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_crypto_deposits', to=settings.AUTH_USER_MODEL)),
                ('crypto_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='bank.cryptowallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
