# Generated by Django 5.0.6 on 2026-01-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_supportconversation_supportmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings Account'), ('FIXED_DEPOSIT', 'Fixed Deposit Account'), ('CURRENT', 'Current Account'), ('BUSINESS', 'Business Account'), ('INVESTMENT', 'Investment Account'), ('SYSTEM', 'System')], default='CHECKING', max_length=20),
        ),
    ]
