# Generated by Django 5.0.6 on 2026-01-28 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_customerprofile_country_customerprofile_middle_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=19, unique=True)),
                ('card_holder_name', models.CharField(max_length=255)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('card_type', models.CharField(choices=[('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('BUSINESS', 'Business')], default='STANDARD', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('daily_limit', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('is_online_enabled', models.BooleanField(default=True)),
                ('is_contactless_enabled', models.BooleanField(default=True)),
                ('is_international_enabled', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_virtual_cards', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_cards', to='bank.customerprofile')),
                ('linked_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_cards', to='bank.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
