# Generated by Django 5.0.6 on 2026-01-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_customerprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TRANSACTION', 'Transaction'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('KYC', 'KYC Update'), ('SECURITY', 'Security Alert'), ('SYSTEM', 'System Notification'), ('VIRTUAL_CARD', 'Virtual Card'), ('CRYPTO', 'Crypto Deposit'), ('SUPPORT', 'Support Message')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bank.customerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='bank_notifi_custome_a98eb4_idx'), models.Index(fields=['customer', 'is_read'], name='bank_notifi_custome_2aed75_idx')],
            },
        ),
    ]
