# Generated by Django 5.0.6 on 2026-01-29 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('WITHDRAWAL', 'Withdrawal'), ('EXTERNAL_TRANSFER', 'External Transfer'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_PAYMENT', 'Loan Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRANSACTION', 'Transaction'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('KYC', 'KYC Update'), ('SECURITY', 'Security Alert'), ('SYSTEM', 'System Notification'), ('VIRTUAL_CARD', 'Virtual Card'), ('CRYPTO', 'Crypto Deposit'), ('SUPPORT', 'Support Message'), ('LOAN', 'Loan')], max_length=20),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('BUSINESS', 'Business Loan'), ('MORTGAGE', 'Mortgage'), ('AUTO', 'Auto Loan'), ('EDUCATION', 'Education Loan')], max_length=20)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate percentage', max_digits=5, null=True)),
                ('term_months', models.IntegerField(help_text='Loan term in months')),
                ('repayment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('SEMI_ANNUAL', 'Semi-Annual'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=20)),
                ('purpose', models.TextField(help_text='Purpose of the loan')),
                ('employment_status', models.CharField(blank=True, max_length=100)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('PAID_OFF', 'Paid Off'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_interest', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('application_data', models.JSONField(blank=True, default=dict, help_text='Additional application data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='bank.customerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField()),
                ('due_date', models.DateField()),
                ('scheduled_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('PARTIAL', 'Partial Payment')], default='SCHEDULED', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.ledgerentry')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bank.loan')),
            ],
            options={
                'ordering': ['payment_number'],
                'unique_together': {('loan', 'payment_number')},
            },
        ),
    ]
