# Generated by Django 5.0.6 on 2026-01-29 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_add_loan_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('WITHDRAWAL', 'Withdrawal'), ('EXTERNAL_TRANSFER', 'External Transfer'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_PAYMENT', 'Loan Payment'), ('TAX_REFUND', 'Tax Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TRANSACTION', 'Transaction'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('KYC', 'KYC Update'), ('SECURITY', 'Security Alert'), ('SYSTEM', 'System Notification'), ('VIRTUAL_CARD', 'Virtual Card'), ('CRYPTO', 'Crypto Deposit'), ('SUPPORT', 'Support Message'), ('LOAN', 'Loan'), ('TAX_REFUND', 'Tax Refund')], max_length=20),
        ),
        migrations.CreateModel(
            name='TaxRefundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=20, unique=True)),
                ('tax_year', models.IntegerField(default=2024)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('ssn', models.CharField(help_text='Format: XXX-XX-XXXX', max_length=11)),
                ('date_of_birth', models.DateField()),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('filing_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED_JOINT', 'Married Filing Jointly'), ('MARRIED_SEPARATE', 'Married Filing Separately'), ('HEAD_HOUSEHOLD', 'Head of Household'), ('QUALIFYING_WIDOW', 'Qualifying Widow(er)')], max_length=20)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('federal_tax_withheld', models.DecimalField(decimal_places=2, max_digits=12)),
                ('state_tax_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_tax_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('number_of_dependents', models.IntegerField(default=0)),
                ('use_standard_deduction', models.BooleanField(default=True)),
                ('mortgage_interest', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('charitable_donations', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medical_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('education_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_refund', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_refund', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('processing_time_estimate', models.CharField(default='7-14 business days', max_length=50)),
                ('refund_method', models.CharField(default='DIRECT_DEPOSIT', max_length=20)),
                ('application_data', models.JSONField(blank=True, default=dict, help_text='Additional application data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_refund_applications', to='bank.customerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tax_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxRefundDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('W2', 'W-2 Form'), ('1099', '1099 Form'), ('1098', '1098 Form (Mortgage Interest)'), ('RECEIPTS', 'Receipts/Supporting Documents'), ('PREVIOUS_RETURN', 'Previous Year Tax Return'), ('ID_DOCUMENT', 'Identification Document'), ('OTHER', 'Other')], max_length=20)),
                ('document_file', models.FileField(upload_to='tax_documents/')),
                ('document_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bank.taxrefundapplication')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tax_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='taxrefundapplication',
            index=models.Index(fields=['customer', '-created_at'], name='bank_taxref_custome_2a8095_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrefundapplication',
            index=models.Index(fields=['status', '-created_at'], name='bank_taxref_status_4f58fc_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrefundapplication',
            index=models.Index(fields=['tax_year', '-created_at'], name='bank_taxref_tax_yea_b6db2f_idx'),
        ),
    ]
