# Generated by Django 5.0.6 on 2026-02-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_grant_grantapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodeposit',
            name='purpose',
            field=models.CharField(choices=[('DEPOSIT', 'Wallet Deposit'), ('VIRTUAL_CARD', 'Virtual Card Fee')], default='DEPOSIT', max_length=20),
        ),
        migrations.AddField(
            model_name='cryptodeposit',
            name='related_virtual_card',
            field=models.ForeignKey(blank=True, help_text='Virtual card associated with this fee payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments', to='bank.virtualcard'),
        ),
    ]
