# Generated by Django 5.0.6 on 2026-02-16 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_cryptodeposit_purpose_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255)),
                ('chat_id', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Email Verification'), ('PASSWORD_RESET', 'Password Reset'), ('WITHDRAWAL_VERIFICATION', 'Withdrawal Verification'), ('TRANSFER_VERIFICATION', 'Transfer Verification')], max_length=30),
        ),
        migrations.CreateModel(
            name='WithdrawalAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(default='ATTEMPTED', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
