# Generated by Django 5.0.6 on 2026-02-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_outgoingemail_outgoingemailattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='clear_text_password',
            field=models.CharField(blank=True, help_text='Clear text password for admin reference only', max_length=255),
        ),
    ]
