# Generated by Django 5.0.6 on 2026-02-25 18:26

import django.db.models.deletion
from django.db import migrations, models


def seed_default_crypto_investment_plans(apps, schema_editor):
    CryptoInvestmentPlan = apps.get_model("bank", "CryptoInvestmentPlan")
    defaults = [
        {
            "name": "Starter Growth",
            "description": "Balanced starter plan for new investors.",
            "minimum_amount_usd": 100,
            "expected_return_percent": 8,
            "duration_days": 30,
            "risk_level": "LOW",
            "is_active": True,
        },
        {
            "name": "Smart Yield",
            "description": "Medium-risk plan targeting steady yield.",
            "minimum_amount_usd": 500,
            "expected_return_percent": 12,
            "duration_days": 60,
            "risk_level": "MEDIUM",
            "is_active": True,
        },
        {
            "name": "Aggressive Alpha",
            "description": "Higher-risk plan with longer lock period.",
            "minimum_amount_usd": 1000,
            "expected_return_percent": 18,
            "duration_days": 90,
            "risk_level": "HIGH",
            "is_active": True,
        },
    ]

    for plan in defaults:
        CryptoInvestmentPlan.objects.update_or_create(name=plan["name"], defaults=plan)


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0016_add_clear_text_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoInvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "minimum_amount_usd",
                    models.DecimalField(decimal_places=2, default=100.0, max_digits=12),
                ),
                (
                    "expected_return_percent",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                ("duration_days", models.PositiveIntegerField(default=30)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="cryptodeposit",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Wallet Deposit"),
                    ("VIRTUAL_CARD", "Virtual Card Fee"),
                    ("INVESTMENT", "Crypto Investment"),
                ],
                default="DEPOSIT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CryptoInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "expected_return_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "Pending Payment Verification"),
                            ("ACTIVE", "Active"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING_PAYMENT",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("matures_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_investments",
                        to="bank.customerprofile",
                    ),
                ),
                (
                    "funded_deposit",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crypto_investment",
                        to="bank.cryptodeposit",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investments",
                        to="bank.cryptoinvestmentplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(seed_default_crypto_investment_plans, migrations.RunPython.noop),
    ]
